### ISSUE TITLE
failed to build under both windows and ubuntu

### ISSUE THREAD

**Issue by testcaoy7** [shovon/node-speke#3]
node-gyp report:
bigint@0.4.2 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bigint@0.4.2 install script.
npm ERR! This is most likely a problem with the bigint package,
npm ERR! not with npm itself.

System Linux 3.13.0-29-generic
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE

**Comment by shovon** [comment]
I was afraid that someone might be bit by my use of [bigint](https://github.com/substack/node-bigint). But I was just being too lazy to move away from bigint to [bignum](https://github.com/justmoon/node-bignum), which is a library that would prevent the compilation issue.

I guess now's the time to make the move to bignum.

The reason why some people might have issues compiling bigint is because they don't have [libgmp](https://gmplib.org/) installed.

bignum doesn't need libgmp, since it uses the utilities available in the OpenSSL library, and OpenSSL comes packaged with Node.js (probably for the crypto API that Node.js offers).

**Comment by shovon** [comment]
Either ways, I'm fixing it.

**Comment by shovon** [comment]
@testcaoy7 try the new v0.0.3 of the `speke` npm module.

**Comment by testcaoy7** [comment]
I have tried new version and it works fine.
Thank you.
